spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ritvik
    username: root
    password: Ritvik@123

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      ddl_auto: create


